- name: Install cuDNN and TensorRT
  become: true
  ansible.builtin.apt:
    name:
#      - libcudnn8={{ cudnn_version }}
#      - libnvinfer8={{ tensorrt_version }}
#      - libnvinfer-plugin8={{ tensorrt_version }}
#      - libnvparsers8={{ tensorrt_version }}
#      - libnvonnxparsers8={{ tensorrt_version }}
      - libcudnn9-headers-cuda-12={{ cudnn_version }}
      - libcudnn9-cuda-12={{ cudnn_version }}
      - libnvinfer10={{ tensorrt_version }}
      - libnvinfer-plugin10={{ tensorrt_version }}
      - libnvonnxparsers10={{ tensorrt_version }}
      
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true

- name: Install cuDNN and TensorRT Dev
  become: true
  ansible.builtin.apt:
    name:
#      - libcudnn8-dev={{ cudnn_version }}
#      - libnvinfer-headers-dev={{ tensorrt_version }}
#      - libnvinfer-headers-plugin-dev={{ tensorrt_version }}
#      - libnvinfer-dev={{ tensorrt_version }}
#      - libnvinfer-plugin-dev={{ tensorrt_version }}
#      - libnvparsers-dev={{ tensorrt_version }}
#      - libnvonnxparsers-dev={{ tensorrt_version }}
      - libcudnn9-dev-cuda-12={{ cudnn_version }}
      - libnvinfer-headers-dev={{ tensorrt_version }}
      - libnvinfer-headers-plugin-dev={{ tensorrt_version }}
      - libnvinfer-dev={{ tensorrt_version }}
      - libnvinfer-plugin-dev={{ tensorrt_version }}
      - libnvonnxparsers-dev={{ tensorrt_version }}
      
    allow_change_held_packages: true
    allow_downgrade: true
    update_cache: true
  when: tensorrt_install_devel | bool

# apt-mark hold
- name: Prevent CUDA-related packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
#    - libcudnn8
#    - libnvinfer8
#    - libnvinfer-plugin8
#    - libnvparsers8
#    - libnvonnxparsers8
    - libcudnn9-headers-cuda-12
    - libcudnn9-cuda-12
    - libnvinfer10
    - libnvinfer-plugin10
    # libnvparsers は削除
    - libnvonnxparsers10

- name: Prevent CUDA-related Dev packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
#    - libcudnn8-dev
#    - libnvinfer-dev
#    - libnvinfer-plugin-dev
#    - libnvparsers-dev
#    - libnvonnxparsers-dev
    - libcudnn9-dev-cuda-12
    - libnvinfer-dev
    - libnvinfer-plugin-dev
    # libnvparsers-dev は削除
    - libnvonnxparsers-dev
  when: tensorrt_install_devel | bool
